

services:
  mongo:
    image: mongo:6
    container_name: exaltt3-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./college-review-backend
      dockerfile: Dockerfile
    container_name: exaltt3-backend
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exaltt3-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network
    restart: always

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
